import { json, type MetaFunction } from '@remix-run/cloudflare';
import { PublicLayout } from '~/components/layouts/PublicLayout';

export const meta: MetaFunction = () => {
  return [
    { title: 'Terms of Service - NoeffortsAI' },
    { name: 'description', content: 'NoeffortsAI terms of service and usage guidelines.' },
  ];
};

export const loader = () => json({});

export default function TermsPage() {
  return (
    <PublicLayout>
      <section className="pt-20 pb-32 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-noeffortsai-elements-textPrimary mb-8">Terms of Service</h1>
          <div className="prose prose-invert max-w-none">
            <p className="text-noeffortsai-elements-textSecondary mb-6">
              Last updated: {new Date().toLocaleDateString()}
            </p>

            <div className="space-y-8 text-noeffortsai-elements-textSecondary">
              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  1. Acceptance of Terms
                </h2>
                <p>
                  By accessing or using NoeffortsAI ("the Service"), you agree to be bound by these Terms of Service. If
                  you do not agree to these terms, you may not use the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  2. Description of Service
                </h2>
                <p>
                  NoeffortsAI is an AI-powered web development platform that allows users to create, edit, and deploy
                  web applications using natural language prompts and AI assistance. The Service may include
                  integrations with third-party AI providers.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">3. User Accounts</h2>
                <p className="mb-4">
                  To access certain features, you may need to create an account. You are responsible for:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Maintaining the confidentiality of your account credentials</li>
                  <li>All activities that occur under your account</li>
                  <li>Notifying us immediately of any unauthorized use</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">4. Acceptable Use</h2>
                <p className="mb-4">You agree not to use the Service to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Generate malicious code or malware</li>
                  <li>Create content that violates any laws or regulations</li>
                  <li>Infringe on intellectual property rights</li>
                  <li>Attempt to breach or circumvent security measures</li>
                  <li>Abuse or overload the Service infrastructure</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  5. Intellectual Property
                </h2>
                <p>
                  You retain ownership of code and content you create using NoeffortsAI. However, you grant us a license
                  to host, store, and display your content as necessary to provide the Service. The NoeffortsAI
                  platform, including its design, features, and underlying technology, remains our intellectual
                  property.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  6. Third-Party Services
                </h2>
                <p>
                  The Service integrates with third-party AI providers. Your use of these integrations is subject to
                  their respective terms of service. We are not responsible for the content generated by third-party AI
                  models.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  7. Disclaimer of Warranties
                </h2>
                <p>
                  THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THAT THE SERVICE
                  WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. AI-GENERATED CODE MAY CONTAIN BUGS OR SECURITY
                  VULNERABILITIES.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  8. Limitation of Liability
                </h2>
                <p>
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
                  OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">
                  9. Changes to Terms
                </h2>
                <p>
                  We reserve the right to modify these terms at any time. We will notify users of significant changes.
                  Continued use of the Service after changes constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-noeffortsai-elements-textPrimary mb-4">10. Contact</h2>
                <p>
                  For questions about these Terms of Service, please contact us through our GitHub repository or Discord
                  community.
                </p>
              </section>
            </div>
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
